<?php

return [
    'admin' => [
        'AdminController@index',
        'CategoriesController@index',
        'CategoriesController@create',
        'CategoriesController@edit',
        'CategoriesController@destroy',
        'CategoriesController@update',
        'CategoriesController@store',

        'PostsController@index',
        'PostsController@create',
        'PostsController@edit',
        'PostsController@destroy',
        'PostsController@update',
        'PostsController@store',

        'ModulesController@index',
        'ModulesController@create',
        'ModulesController@edit',
        'ModulesController@destroy',
        'ModulesController@update',
        'ModulesController@store',

        'DeliveriesController@index',
        'DeliveriesController@create',
        'DeliveriesController@edit',
        'DeliveriesController@destroy',
        'DeliveriesController@update',
        'DeliveriesController@store',


        'BannersController@index',
        'BannersController@create',
        'BannersController@edit',
        'BannersController@destroy',
        'BannersController@update',
        'BannersController@store',

        'PositionsController@index',
        'PositionsController@create',
        'PositionsController@edit',
        'PositionsController@destroy',
        'PositionsController@update',
        'PositionsController@store',

        'ProductsController@index',
        'ProductsController@create',
        'ProductsController@edit',
        'ProductsController@destroy',
        'ProductsController@update',
        'ProductsController@store',

        'TagsController@index',
        'TagsController@create',
        'TagsController@edit',
        'TagsController@destroy',
        'TagsController@update',
        'TagsController@store',

        'VideosController@index',
        'VideosController@create',
        'VideosController@edit',
        'VideosController@destroy',
        'VideosController@update',
        'VideosController@store',

        'QuestionsController@index',
        'QuestionsController@create',
        'QuestionsController@edit',
        'QuestionsController@destroy',
        'QuestionsController@update',
        'QuestionsController@store',

        'ContactsController@index',
        'ContactsController@create',
        'ContactsController@edit',
        'ContactsController@destroy',
        'ContactsController@update',
        'ContactsController@store',


    ],

    'editor' => [
        'AdminController@index',
        'CategoriesController@index',
        'CategoriesController@create',
        'CategoriesController@edit',
        'CategoriesController@destroy',
        'CategoriesController@update',
        'CategoriesController@store',

        'PostsController@index',
        'PostsController@create',
        'PostsController@edit',
        'PostsController@destroy',
        'PostsController@update',
        'PostsController@store',

        'ModulesController@index',
        'ModulesController@create',
        'ModulesController@edit',
        'ModulesController@destroy',
        'ModulesController@update',
        'ModulesController@store',

        'DeliveriesController@index',
        'DeliveriesController@create',
        'DeliveriesController@edit',
        'DeliveriesController@destroy',
        'DeliveriesController@update',
        'DeliveriesController@store',


        'BannersController@index',
        'BannersController@create',
        'BannersController@edit',
        'BannersController@destroy',
        'BannersController@update',
        'BannersController@store',

        'PositionsController@index',
        'PositionsController@create',
        'PositionsController@edit',
        'PositionsController@destroy',
        'PositionsController@update',
        'PositionsController@store',

        'ProductsController@index',
        'ProductsController@create',
        'ProductsController@edit',
        'ProductsController@destroy',
        'ProductsController@update',
        'ProductsController@store',

        'TagsController@index',
        'TagsController@create',
        'TagsController@edit',
        'TagsController@destroy',
        'TagsController@update',
        'TagsController@store',

        'VideosController@index',
        'VideosController@create',
        'VideosController@edit',
        'VideosController@destroy',
        'VideosController@update',
        'VideosController@store',

        'QuestionsController@index',
        'QuestionsController@create',
        'QuestionsController@edit',
        'QuestionsController@destroy',
        'QuestionsController@update',
        'QuestionsController@store',

        'ContactsController@index',
        'ContactsController@create',
        'ContactsController@edit',
        'ContactsController@destroy',
        'ContactsController@update',
        'ContactsController@store',
    ]
];